# 1.3 NumPy - Algebra liniowa

NumPy jest pakietem wykorzystywanym do obliczeń w dziedzinie algebry liniowej, co jeszcze szczególnie przydatne w uczeniu maszynowym. 

Wektor o wymiarach $1 \times N$ 
$$
    X =
    \begin{pmatrix}
    x_{1}  \\
    x_{2}  \\
    \vdots \\
    x_{N}
    \end{pmatrix} 
$$

i jego transpozycję $\mathbf{x}^{T} = (x_{1}, x_{2},\ldots,x_{N})$ można wyrazić w Pythonie w następujący sposób:

In [1]:
import numpy as np

x = np.array([[1,2,3]]).T
x.shape

(3, 1)

In [2]:
xt = x.T
xt.shape

(1, 3)

**Macierz kolumnowa** w NumPy.
$$X =
    \begin{pmatrix}
    3  \\
    4  \\
    5  \\
    6  
    \end{pmatrix}$$

In [5]:
x = np.array([[3,4,5,6]]).T
x

array([[3],
       [4],
       [5],
       [6]])

**Macierz wierszowa** w NumPy.
$$ X =
    \begin{pmatrix}
    3 & 4 & 5 & 6
    \end{pmatrix}$$

In [6]:
x = np.array([[3,4,5,6]])
x

array([[3, 4, 5, 6]])

## Obiekty typ `matrix`

Macierze ogólne zostały omówione już wcześniej:

$$A_{m,n} =
    \begin{pmatrix}
     a_{1,1} & a_{1,2} & \cdots & a_{1,n} \\
     a_{2,1} & a_{2,2} & \cdots & a_{2,n} \\
     \vdots  & \vdots  & \ddots & \vdots  \\
     a_{m,1} & a_{m,2} & \cdots & a_{m,n}
    \end{pmatrix}$$

Oprócz obiektów typu `array` istnieje wyspecjalizowany obiekt `matrix`, dla którego operacje `*` (mnożenie) oraz `**-1` (odwracanie) są określone w sposób właściwy dla macierzy (w przeciwieństwie do operacji elementowych dla obiektów `array`).

In [7]:
x = np.array([1,2,3,4,5,6,7,8,9]).reshape(3,3)
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
X = np.matrix(x)
X

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

## Operacje na macierzach
### Wyznacznik

In [9]:
a = np.array([[3,-9],[2,5]])
np.linalg.det(a)

33.000000000000014

### Macierz odwrotna

In [10]:
A = np.array([[-4,-2],[5,5]])
A

array([[-4, -2],
       [ 5,  5]])

In [11]:
invA = np.linalg.inv(A)
invA

array([[-0.5, -0.2],
       [ 0.5,  0.4]])

In [12]:
np.round(np.dot(A,invA))

array([[ 1.,  0.],
       [ 0.,  1.]])

Ponieważ $AA^{-1} = A^{-1}A = I$.

### Wartości i wektory własne

In [13]:
a = np.diag((1, 2, 3))
a

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [14]:
w,v = np.linalg.eig(a)
w

array([ 1.,  2.,  3.])

In [15]:
v

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])