# 1.1 NumPy - Tablice

## Wprowadzenie

Głównym obiektem w NumPy jest **jednorodna**, **wielowymiarowa** tablica. Przykładem takiej tablicy jest macierz `x`.

Macierz $x =
    \begin{pmatrix}
    1 & 2 & 3  \\
    4 & 5 & 6  \\
    7 & 8 & 9
    \end{pmatrix}$
można zapisać jako:

In [8]:
import numpy as np

x = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Najczęsciej używane metody tablic typu `array`:

In [7]:
x.shape

(3, 4)

In [4]:
x.sum(axis=0)

array([12, 15, 18])

In [5]:
x.mean(axis=1)

array([ 2.,  5.,  8.])

Do tworzenia sekwencji liczbowych jako obiekty typu `array` należy wykorzystać funkcję `arange`.

In [9]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [11]:
np.arange(5,10,0.5)

array([ 5. ,  5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5])

Kształt tablicy można zmienić za pomocą metody `reshape`:

In [12]:
x = np.arange(1,10).reshape(3,3)
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Funkcją podobną do `arange` jest `linspace`, która wypełnia wektor określoną liczbą elementów z przedziału o równych automatycznie obliczonych odstępach (w `arange` należy podać rozmiar kroku):

In [13]:
x = np.linspace(0,5,5)

Dodatkowe informacje o funkcjach NumPy uzyskuje się za pomocą polecenia `help(nazwa_funkcji)`:

In [14]:
help(np.shape)

Help on function shape in module numpy.core.fromnumeric:

shape(a)
    Return the shape of an array.
    
    Parameters
    ----------
    a : array_like
        Input array.
    
    Returns
    -------
    shape : tuple of ints
        The elements of the shape tuple give the lengths of the
        corresponding array dimensions.
    
    See Also
    --------
    alen
    ndarray.shape : Equivalent array method.
    
    Examples
    --------
    >>> np.shape(np.eye(3))
    (3, 3)
    >>> np.shape([[1, 2]])
    (1, 2)
    >>> np.shape([0])
    (1,)
    >>> np.shape(0)
    ()
    
    >>> a = np.array([(1, 2), (3, 4)], dtype=[('x', 'i4'), ('y', 'i4')])
    >>> np.shape(a)
    (2,)
    >>> a.shape
    (2,)



Tablice mogą składać się z danych różnych typów (ale tylko jednego typu danych równocześnie, stąd jednorodność).

In [15]:
x = np.array([1,2,3])
print(x.dtype)
x = np.array([0.1,0.2,0.3])
print(x)
print(x.dtype)
x = np.array([1,2,3],dtype='float64')
print(x.dtype)

int64
[ 0.1  0.2  0.3]
float64
float64


Tworzenie tablic składających się z samych zer lub jedynek umożliwiają funkcje `zeros` oraz `ones`:

In [16]:
x = np.zeros([3,4])
x

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [17]:
x = np.ones([3,4])
x

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

### Wykonaj zadania 1.1 z notatnika z zadaniami