# 1.2 NumPy - Podstawowe funkcje

* `a.ndim` - zwraca liczbę wymiarów tablicy `a`
* `a.shape` - zwraca liczbę wierszy i kolumn tablicy `a`
* `arange(start,stop,step)` - zwraca wektor sekwencji
* `linspace(start,stop,steps)` - zwraca sekwencję o równych odstępach z określonego przedziału
* `dot(a,b)` - mnoży macierze `a` i `b`
* `vstack([a,b])` - pionowo skleja tablice `a` i `b`
* `hstack([a,b])` - poziomo skleja tablice `a` i `b`
* `where(a>x)` - zwraca elementy tablicy spełniające podany warunek

## Podstawowe operacje arytmetyczne

Operatory arytmetyczne działają w NumPy **element po elemencie**.

In [1]:
import numpy as np

a = np.array([3,4,5])
b = np.ones(3)
a - b

array([ 2.,  3.,  4.])

Za mnożenie macierzy odpowiada funkcja `dot` (nie operator `*`):

In [2]:
a = np.array([[1,2],[3,4]])
b = np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [3]:
a * b

array([[ 1,  4],
       [ 9, 16]])

In [4]:
np.dot(a,b)

array([[ 7, 10],
       [15, 22]])

Przykłady innych operacji dodawania i mnożenia:

In [5]:
a = np.zeros((2,2),dtype='float')
a += 5
a

array([[ 5.,  5.],
       [ 5.,  5.]])

In [6]:
a *= 5
a

array([[ 25.,  25.],
       [ 25.,  25.]])

In [7]:
a + a

array([[ 50.,  50.],
       [ 50.,  50.]])

Sklejanie tablic:

In [8]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([7,8,9])
np.hstack([a,b,c])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.vstack([a,b,c])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Typowe funkcje matematyczne:

In [10]:
x = np.arange(1,5)
np.sqrt(x) * np.pi 

array([ 3.14159265,  4.44288294,  5.44139809,  6.28318531])

In [11]:
2**4

16

In [12]:
np.power(2,4)

16

In [13]:
np.log(np.e)

1.0

In [14]:
x = np.arange(5)
x.max() - x.min()

4

## Indeksy i zakresy
Tablice jednowymiarowe zachowują sie podobnie do zwykłych list pythonowych.

In [15]:
a = np.arange(10)
a[2:4]

array([2, 3])

In [16]:
a[:10:2]

array([0, 2, 4, 6, 8])

In [17]:
a[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

Tablice wielowymiarowe mają po jednym indeksie na wymiar:

In [18]:
x = np.arange(12).reshape(3,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [19]:
x[2,3]

11

In [20]:
x[:,1]

array([1, 5, 9])

In [21]:
x[1,:]

array([4, 5, 6, 7])

In [22]:
x[1:3,:]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

## Warunki
Pozwalają na selekcję elementów tablicy.


In [23]:
a = np.array([1,1,1,2,2,2,3,3,3])
a[a>1]

array([2, 2, 2, 3, 3, 3])

In [24]:
a[a==3]

array([3, 3, 3])

In [25]:
np.where(a<3)

(array([0, 1, 2, 3, 4, 5]),)

In [26]:
np.where(a<3)[0]

array([0, 1, 2, 3, 4, 5])

In [27]:
np.where(a>9)

(array([], dtype=int64),)

## Pętle i drukowanie


In [28]:
for row in x:
    print row

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [29]:
for element in x.flat:
    print element, 

0 1 2 3 4 5 6 7 8 9 10 11


## Liczby losowe

In [30]:
np.random.randint(0,10,5) 

array([7, 7, 7, 3, 5])

In [31]:
np.random.normal(0,1,5) 

array([ 0.17724687,  0.30344145, -0.72748394,  0.1596293 ,  0.64758324])

In [32]:
np.random.uniform(0,2,5)

array([ 1.96534994,  1.58120735,  0.59330655,  1.41794067,  0.31967502])